/**
 *
 */
package jp.ac.asojuku.typing.param;

/**
 * エラーコード
 * @author nishino
 *
 */
public enum ErrorCode {

	SUCCESS("errmsg0000") ,
	//ログイン(00xx)
	ERR_LOGIN("errmsg0001"),
	//会員登録(01xx)
	ERR_MEMBER_ENTRY_MAILADDRESS("errmsg0101"),
	ERR_MEMBER_ENTRY_NAME("errmsg0102"),
	ERR_MEMBER_ENTRY_ADDRESS("errmsg0103"),
	ERR_MEMBER_ENTRY_TELNUMBER("errmsg0104"),
	ERR_MEMBER_ENTRY_MAILADDRESS_ISNEED("errmsg0105"),
	ERR_MEMBER_ENTRY_NAME_ISNEED("errmsg0106"),
	ERR_MEMBER_ENTRY_ADDRESS_ISNEED("errmsg0107"),
	ERR_MEMBER_ENTRY_TELNUMBER_ISNEED("errmsg0108"),
	ERR_MEMBER_ENTRY_PASSWORD_NOTMATCH("errmsg0109"),
	ERR_MEMBER_ENTRY_PASSWORD_POLICY("errmsg0110"),
	ERR_MEMBER_ENTRY_DUPLICATE_MEIL("errmsg0111"),
	ERR_MEMBER_ENTRY_NICKNAME("errmsg0113"),
	ERR_MEMBER_ENTRY_NICKNAME_ISNEED("errmsg0112"),
	ERR_MEMBER_ENTRY_COURSEID_ERR("errmsg0114"),
	ERR_MEMBER_ENTRY_ADMISSIONYEAR("errmsg0115"),
	ERR_MEMBER_ENTRY_ADMISSIONYEAR_ERR("errmsg0116"),
	ERR_MEMBER_ENTRY_GRADUATEYEAR("errmsg0117"),
	ERR_MEMBER_ENTRY_GRADUATE_ERR("errmsg0118"),
	ERR_MEMBER_ENTRY_GIVEUPYEAR("errmsg0119"),
	ERR_MEMBER_ENTRY_GIVEUP_ERR("errmsg0120"),
	ERR_MEMBER_ENTRY_ROLEID_ERR("errmsg0121"),
	ERR_MEMBER_ENTRY_DIFFICALTY_ERR("errmsg0122"),
	ERR_MEMBER_ENTRY_MAILNOTFOUND_ERR("errmsg0123"),
	ERR_MEMBER_ENTRY_DUPLICATE_STUDENTNO("errmsg0124"),
	//ルーム関連(02xx)
	ERR_ROOM_NAME_ISNEED("errmsg0201"),
	ERR_ROOM_NAME_ERROR("errmsg0202"),
	ERR_ROOM_ADMIN_ISNEED("errmsg0203"),
	ERR_ROOM_BELONG_ISNEED("errmsg0204"),
	ERR_ROOM_ADMIN_FMT_ERROR("errmsg0205"),
	ERR_ROOM_BELONG_FMT_ERROR("errmsg0206"),
	ERR_ROOM_MAIL_NOT_FOUND("errmsg0207"),
	ERR_ROOM_DUPLICATE_ROOMNAME("errmsg0208"),
	ERR_ROOM_ADMIN_MAIL_NOT_FOUND("errmsg0209"),
	ERR_ROOM_USER_MAIL_NOT_FOUND("errmsg0210"),
	
	//掲示板関連(03xx)
	ERR_CSV_FORMAT_ERROR("errmsg0401"),
	//お知らせ関連(04xx)
	ERR_INFO_TITLE_LEN("errmsg0401"),
	ERR_INFO_MSG_LEN("errmsg0402"),
	
	//パスワード関連
	ERR_PWD_CHG_NOT_MATCH("errmsg0501"),
	ERR_PWD_CHG_OLD_PWD_EMPTY("errmsg0502"),
	ERR_PWD_CHG_NEW_PWD_EMPTY("errmsg0503"),
	ERR_PWD_CHG_OLD_PWD_WRONG("errmsg0504"),
	ERR_PWD_CHG_MAIL_EMPTY("errmsg0505"),
	ERR_PWD_CHG_MAIL_NOTEXIST("errmsg0506"),
	
	ERR_SKILL_NAME_DUPLICATE("errmsg0601"),

	//その他のエラー
	ERR_INVLIDATE("errmsg9901"),
	ERR_SYSTEM_ERROR("errmsg9999"),
	;

	private String code;

	private ErrorCode(String code){ this.code = code; }

	public String getCode(){ return code; }
	public String toString() { return code; }

}
