package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * ダウンロード解答テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="ANS_DL_TBL")
public class AnsDlTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ansid. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer ansid;

	/** ユーザーテーブル. */
	private Integer uid;	//更新用 
	@OneToOne
    @JoinColumn(name="uid",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** 新規テーブル. */
	private Integer edId;	//更新用
	@OneToOne
    @JoinColumn(name="edId",insertable=false ,updatable=false)
	private EventDownloadEntity eventDownload;

	/** submit_date. */
	private Date submitDate;

	/**
	 * コンストラクタ.
	 */
	public AnsDlTblEntity() {
	}

	/**
	 * ansid を設定します.
	 * 
	 * @param ansid
	 *            ansid
	 */
	public void setAnsid(Integer ansid) {
		this.ansid = ansid;
	}

	/**
	 * ansid を取得します.
	 * 
	 * @return ansid
	 */
	public Integer getAnsid() {
		return this.ansid;
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param userTbl
	 *            ユーザーテーブル
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * 新規テーブル を設定します.
	 * 
	 * @param eventDownload
	 *            新規テーブル
	 */
	public void setEventDownload(EventDownloadEntity eventDownload) {
		this.eventDownload = eventDownload;
	}

	/**
	 * 新規テーブル を取得します.
	 * 
	 * @return 新規テーブル
	 */
	public EventDownloadEntity getEventDownload() {
		return this.eventDownload;
	}

	/**
	 * submit_date を設定します.
	 * 
	 * @param submitDate
	 *            submit_date
	 */
	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	/**
	 * submit_date を取得します.
	 * 
	 * @return submit_date
	 */
	public Date getSubmitDate() {
		return this.submitDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ansid == null) ? 0 : ansid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AnsDlTblEntity other = (AnsDlTblEntity) obj;
		if (ansid == null) {
			if (other.ansid != null) {
				return false;
			}
		} else if (!ansid.equals(other.ansid)) {
			return false;
		}
		return true;
	}

}
