package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

import lombok.Data;

/**
 * ダウンロード解答テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="ANS_DL_TBL")
public class AnsDlTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ansid. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer ansid;

	/** ユーザーテーブル. */
	private Integer uid;	//更新用 
	@OneToOne
    @JoinColumn(name="uid",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** 新規テーブル. */
	private Integer edId;	//更新用
	@OneToOne
    @JoinColumn(name="edId",insertable=false ,updatable=false)
	private EventDownloadEntity eventDownload;

	/** submit_date. */
	private Date submitDate;
	
	private String ansFilepath;

	@PrePersist
    public void onPrePersist() {
		setSubmitDate(new Date());
    }

    @PreUpdate
    public void onPreUpdate() {
		setSubmitDate(new Date());
    }

}
