package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * 新規テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="DOWNLOAD_TBL")
public class DownloadTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** download_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer downloadId;

	/** ordinal_num. */
	private Integer ordinalNum;

	/** filename. */
	private String filename;



}
