package jp.ac.asojuku.typing.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * イベントユーザー モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="EVENT_USER")
public class EventUserEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** euid. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer euid;

	/** ユーザーテーブル. */
	private Integer uid;
	@OneToOne
    @JoinColumn(name="uid",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** イベントテーブル. */
	private Integer eid;
	@OneToOne
    @JoinColumn(name="eid",insertable=false ,updatable=false)
	private EventTblEntity eventTbl;

	/** del_flg. */
	private Integer delFlg;


}
