package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * イベント問題文 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="EVENT_QUESTION")
public class EventQuestionEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** eqid. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer eqid;

	/** no. */
	private Integer no;

	/** イベントテーブル. */
	private Integer eid;
	@OneToOne
    @JoinColumn(name="eid",insertable=false ,updatable=false)
	private EventTblEntity eventTbl;

	/** 問題テーブル. */
	private Integer qid;
	@OneToOne
    @JoinColumn(name="qid",insertable=false ,updatable=false)
	private QestionTblEntity qestionTbl;


}
