package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * イベントテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="EVENT_TBL")
public class EventTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** eid. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer eid;

	/** name. */
	private String name;

	/** public_date. */
	private Date publicDate;

	/** start_date. */
	private Date startDate;

	/** finish_date. */
	private Date finishDate;
	
	/** public_end_date. */
	private Date publicEndDate;

	/** ower_name. */
	private String owerName;

	/** rankingdisplay. */
	private Integer rankingdisplay;

	/** hiderankingtime. */
	private Integer hiderankingtime;

	/** filter. */
	private String filter;

	/** イベント問題文 一覧. */
	//private Integer eqid;
	//@OneToMany(cascade = CascadeType.ALL)
	//@JoinColumn(name="eqid",insertable=true ,updatable=true)
	//private Set<EventQuestionEntity> eventQuestionSet;

	/** イベントユーザー 一覧. */
	//private Integer euid;
	//@OneToMany(cascade = CascadeType.ALL)
	//@JoinColumn(name="euid",insertable=true ,updatable=true)
	//private Set<EventUserEntity> eventUserSet;

	/**
	 * コンストラクタ.
	 */
	public EventTblEntity() {
//		this.eventQuestionSet = new HashSet<EventQuestionEntity>();
//		this.eventUserSet = new HashSet<EventUserEntity>();
	}


}
