package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 新規テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="EVENT_DOWNLOAD")
public class EventDownloadEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ed_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer edId;

	/** イベントテーブル. */
	private Integer eid;
	@OneToOne
    @JoinColumn(name="eid",insertable=false ,updatable=false)
	private EventTblEntity eventTbl;

	/** 新規テーブル. */
	private Integer downloadId;
	@OneToOne
    @JoinColumn(name="downloadId",insertable=false ,updatable=false)
	private DownloadTblEntity downloadTbl;
	
	private Integer no;


}
