package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * 問題テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="QUESTION_TBL")
public class QestionTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** qid. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer qid;

	/** title. */
	private String title;

	/** sentence. */
	private String sentence;

	/** practiceflg. */
	private Integer practiceflg;

	/** difficalty. */
	private Integer difficalty;

	/** count. */
	private Integer count;



}
