package jp.ac.asojuku.typing.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ユーザーテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="USER_TBL")
public class UserTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** uid. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer uid;

	/** mail. */
	private String mail;

	/** password. */
	private String password;

	/** name. */
	private String name;

	/** disp_name. */
	private String dispName;

	/** affiliation. */
	private String affiliation;

	/** role. */
	private Integer role;

	/** del_flg. */
	private Integer delFlg;


}
